FinalProject_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from projects import views as project_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import handler500

handler500 = project_views.page_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('', project_views.project_list, name='home'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG is False:
#     urlpatterns += patterns('', url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT, }), )

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout')
]

projects/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler500

handler500 = views.page_error
app_name = 'projects'
urlpatterns = [
    path('', views.project_list, name="list"),
    path('initial/', views.create_initial, name="initial"),
    path('classification_create/', views.classification_create, name="classification_create"),
    path('regression_create/', views.regression_create, name="regression_create"),
    path('classification_process/<int:project_id>/', views.classification_process, name="classification_process"),
    path('regression_process/<int:project_id>/', views.regression_process, name="regression_process"),
    path('classification_train/<int:project_id>/', views.classification_train, name="classification_train"),
    path('regression_train/<int:project_id>/', views.regression_train, name="regression_train"),
    path('classification_predict/<int:project_id>/', views.classification_predict, name="classification_predict"),
    path('regression_predict/<int:project_id>/', views.regression_predict, name="regression_predict"),
    path('classification_result/<int:project_id>/', views.classification_result, name="classification_result"),
    path('regression_result/<int:project_id>/', views.regression_result, name="regression_result"),
    path('project_comment/<int:project_id>/', views.project_addcomment, name="comment"),
    path('individual/<slug:user_name>/', views.individual_list, name="individual_list"),
    path('<int:project_id>/', views.project_detail, name="detail"),


]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length = 100)
    description = models.TextField(blank=True)
    predict_type = models.CharField(max_length=100,blank=True)
    creator = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True) #automatically added when created.
    labeled_data = models.FileField(upload_to='labeled_data')
    attribute_num = models.IntegerField(null=True)
    accurate_list = models.TextField(blank=True)
    accurate_rate = models.CharField(blank=True, max_length = 50)
    mean_squared_error = models.CharField(blank=True, max_length = 50)
    algorithm_selected = models.CharField(blank=True, max_length = 50)
    unlabeled_data = models.CharField(max_length=500)
    predict_result = models.TextField(blank=True)
    comment = models.TextField(blank=True)



    def __str__(self):
        return self.title

projects/forms.py
from django import forms
from . import models


class CreateProject(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['title', 'description', 'labeled_data']


class ClassificationPredict(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['unlabeled_data']

projects/views.py
from django.shortcuts import render, redirect
from .models import Project
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from . import forms
from django.http import HttpResponseRedirect
from django.core.files import File
from . import classify
from . import regression
from django.shortcuts import render_to_response
from . import read_attributes_num
import os



def project_list(request):
    projects = Project.objects.all().order_by('date')
    return render(request, 'projects/project_list.html',{'projects':projects})


def project_detail(request, project_id):
    project = Project.objects.get(pk=project_id)
    return render(request, 'projects/project_detail.html',{'project':project})


@login_required(login_url="accounts:login")
def individual_list(request, user_name):
    projects = Project.objects.filter(creator__username__exact=user_name)
    return render(request, 'projects/individual_list.html',{'projects':projects})


@login_required(login_url="accounts:login")
def create_initial(request):
    return render(request, 'projects/project_initial.html')


@login_required(login_url="accounts:login")
def classification_create(request):
    if request.method == 'POST':
        form=forms.CreateProject(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.creator=request.user
            instance.save()
            project_id = instance.id
            return redirect(reverse('projects:classification_process', args=[project_id]))
    else:
        form = forms.CreateProject()
    return render(request, 'projects/classification_create.html', { 'form':form })


@login_required(login_url="accounts:login")
def regression_create(request):
    if request.method == 'POST':
        form=forms.CreateProject(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.creator=request.user
            instance.save()
            project_id = instance.id
            return redirect(reverse('projects:regression_process', args=[project_id]))
    else:
        form = forms.CreateProject()
    return render(request, 'projects/regression_create.html', { 'form':form })


@login_required(login_url="accounts:login")
def classification_process(request, project_id):
    project = Project.objects.get(pk=project_id)
    project.predict_type = "classification"
    project.save()
    return render(request, 'projects/classification_process.html',{ 'project':project })


@login_required(login_url="accounts:login")
def regression_process(request, project_id):
    project = Project.objects.get(pk=project_id)
    project.predict_type = "regression"
    project.save()
    return render(request, 'projects/regression_process.html',{ 'project':project })


@login_required(login_url="accounts:login")
def classification_train(request, project_id):
    project = Project.objects.get(pk=project_id)
    training_file = project.labeled_data.name
    training_path = os.path.join('media/', training_file)
    accurate_rate, accurate_list, algorithm_selected = classify.select_best_algorithm(training_path)
    attribute_num = read_attributes_num.read_attributes_num(training_path)
    project.attribute_num = attribute_num
    project.accurate_list = accurate_list
    project.accurate_rate = accurate_rate
    project.algorithm_selected = algorithm_selected
    project.save()
    return render(request, 'projects/classification_train.html',{'project':project})


@login_required(login_url="accounts:login")
def regression_train(request, project_id):
    project = Project.objects.get(pk=project_id)
    training_file = project.labeled_data.name
    training_path = os.path.join('media/',training_file)
    mean_squared_error, squared_error_list, algorithm_selected = regression.select_best_algorithm(training_path)
    attribute_num = read_attributes_num.read_attributes_num(training_path)
    project.attribute_num = attribute_num
    project.accurate_list = squared_error_list
    project.mean_squared_error = mean_squared_error
    project.algorithm_selected = algorithm_selected
    project.save()
    return render(request, 'projects/regression_train.html',{'project':project})


@login_required(login_url="accounts:login")
def classification_predict(request, project_id):
    project = Project.objects.get(pk=project_id)
    project.unlabeled_data = ""
    if request.method == 'POST':
        data_tmp =""
        for d in range(project.attribute_num):
            d_index = "unlabeled"+str(d)
            print(d)
            print(d_index)
            print(request.POST[d_index])
            data_tmp += request.POST[d_index]
            data_tmp += ","
        project.unlabeled_data = data_tmp[:-1]
        project.save()
        return redirect(reverse('projects:classification_result', args=[project_id]))
    else:
        return render(request, 'projects/classification_predict.html', {'project':project}, )

@login_required(login_url="accounts:login")
def regression_predict(request, project_id):
    project = Project.objects.get(pk=project_id)
    project.unlabeled_data =""
    if request.method == 'POST':
        data_tmp =""
        for d in range(project.attribute_num):
            d_index = "unlabeled" + str(d)
            print(d)
            print(d_index)
            print(request.POST[d_index])
            data_tmp += request.POST[d_index]
            data_tmp += ","
        project.unlabeled_data = data_tmp[:-1]
        project.save()
        return redirect(reverse('projects:regression_result', args=[project_id]))
    else:
        return render(request, 'projects/regression_predict.html', {'project':project})


# @login_required(login_url="accounts:login")
# def regression_predict(request, project_id):
#     project = Project.objects.get(pk=project_id)
#     if request.method == 'POST':
#         project.unlabeled_data = request.POST['unlabeled_data']
#         project.save()
#         return redirect(reverse('projects:regression_result', args=[project_id]))
#     else:
#         return render(request, 'projects/regression_predict.html', {'project':project})



@login_required(login_url="accounts:login")
def classification_result(request, project_id):
    project = Project.objects.get(pk=project_id)
    # training_file = project.labeled_data.name
    # training_path = os.path.join('media/',training_file)
    # attribute_str = project.attribute_num
    # attribute_num = int(attribute_str)
    # array_to_predict = project.unlabeled_data
    project.predict_result = classify.input_and_predict(project.algorithm_selected, project.unlabeled_data)
    project.save()
    return render(request, 'projects/classification_result.html',{'project':project})

@login_required(login_url="accounts:login")
def regression_result(request, project_id):
    project = Project.objects.get(pk=project_id)
    project.predict_result = regression.input_and_predict(project.algorithm_selected, project.unlabeled_data)
    project.save()
    return render(request, 'projects/regression_result.html',{'project':project})


@login_required(login_url="accounts:login")
def project_addcomment(request, project_id):
    project = Project.objects.get(pk=project_id)
    if request.method == 'POST':
        project.comment = request.POST['comment']
        project.save()
        return redirect(reverse('projects:list'))
    else:
        return render(request,'projects/project_comment.html',{'project':project})


def page_error(request):
    return render_to_response('projects/500.html')

projects/templates/projects/classification_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-project">
        <h2>Create an Awesome New Classification Project</h2>
        <div class="hint">
        <h3><font color="#FF6347">Hint:</font></h3>
        <p>Please upload .txt file as labeled data file. Each data should be separated by Enter("\n"), each element of data should be separated by Tab("\t").
          Please notice that wrong format of data file will lead to failed prediction.
        </p>
        </div>
        <form class="site-form" action="{% url 'projects:classification_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

projects/templates/projects/classification_predict.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="project-predict">
        <h2>The Result of Prediction</h2>
        <h3>{{ project.title }}</h3>
        <div class="hint">
        <h3><font color="#FF6347">Hint:</font></h3>
        <p>Please input the elements of the unlabeld data that you going to predict.
          Please notice that wrong format of data file will lead to failed prediction.
        </p>
        </div>



        <div class="predict-form">

        <form action="{% url 'projects:classification_predict' project.id %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for i in "x"|ljust:project.attribute_num %}
          <input type="text" name="unlabeled{{ forloop.counter0 }}">
          {% endfor %}
          <input type="submit" value="Predict">
        </form>
      </div>




    </div>
{% endblock %}

projects/templates/projects/classification_process.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="project-processing">
  <div class="project">
      <h2> Uploaded Successfully!</h2>
    <h3>{{ project.title }}</h3>
      <h4><a href="{% url 'projects:classification_train' project.id %}" class="highlight" >Continue</a></h4>

  </div>
</div>



{% endblock %}

projects/templates/projects/classification_train.html
{% extends 'base_layout.html' %}

{% block content%}

<div class="project-training">
  <div class="project">
    <h2>{{ project.title }}</h2>

    <h3>The result of traning: </h3>
    <pre>{{ project.accurate_list }}</pre>

      <h2>The most suitable algorithm for your project is:  {{ project.algorithm_selected }}</h2>
      <h2>The accuracy rate is:  {{ project.accurate_rate }}</h2>

        <div class="continue">
          <h3><a href="{% url 'projects:classification_predict' project.id %}" class="highlight">Continue </a></h3>
        </div>
</div>
</div>



{% endblock %}

projects/templates/projects/individual_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Project List</h1>
    <div class="projects">
    {% for project in projects %}
        <div class="project">
            <h2><a href="{% url 'projects:detail' project.id %}">{{ project.title }}</a></h2>
            <p class="type">Type: {{ project.predict_type }} problem</p>
            <pa class="creator">added by {{ project.creator }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

projects/templates/projects/project_comment.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="project-comment">
        <h2>Comment...</h2>

        <textarea name="comment", form="commentform" >Add Comment...</textarea>

        <div class="comment-form">
        <form action="{% url 'projects:comment' project.id %}" method="post" enctype="multipart/form-data" id="commentform">
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>
      </div>
    </div>
{% endblock %}

projects/templates/projects/project_initial.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="project-initial">
    <h2>Which kind of algorithm you want to implement?</h2>
    <ul>
      <li><a href="{% url 'projects:classification_create' %}">Classification</a></li>
      <li><a href="{% url 'projects:regression_create' %}">Regression</a></li>
<div class="hint">
      <h3><font color="#FF6347">Hint:</font></h3>
      <pre>
      In classification problems we are trying to predict a discrete number of values.
      In regression problems we are trying to predict continuous valued output.
</pre>
</div>
  </ul>
</div>

{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Project List</h1>
    <div class="projects">
    {% for project in projects %}
        <div class="project">
            <h2><a href="{% url 'projects:detail' project.id %}">{{ project.title }}</a></h2>
            <p class="type">Type: {{ project.predict_type }} problem</p>
            <pa class="creator">added by {{ project.creator }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

projects/templates/projects/regression_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-project">
        <h2>Create an Awesome New Regression Project</h2>
        <div class="hint">
        <h3><font color="#FF6347">Hint:</font></h3>
        <p>Please upload .txt file as labeled data file. Each data should be separated by Enter("\n"), each element of data should be separated by Tab("\t").
          Please notice that wrong format of data file will lead to failed prediction.
        </p>
        </div>
        <form class="site-form" action="{% url 'projects:regression_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

projects/templates/projects/regression_predict.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="project-predict">
        <h2>The Result of Prediction</h2>
        <h3>{{ project.title }}</h3>
        <div class="hint">
        <h3><font color="#FF6347">Hint:</font></h3>
        <p>Please Input the elements of the unlabeld data that you going to input.
          Please notice that wrong format of data file will lead to failed prediction.
        </p>
        </div>
        <div class="predict-form">

        <form action="{% url 'projects:regression_predict' project.id %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for i in "x"|ljust:project.attribute_num %}
          <input type="text" name="unlabeled{{ forloop.counter0 }}">
          {% endfor %}
          <input type="submit" value="Predict">
        </form>
      </div>

    </div>
{% endblock %}

projects/templates/projects/regression_process.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="project-processing">
  <div class="project">
      <h2> Uploaded Successfully!</h2>
    <h3>{{ project.title }}</h3>
      <h4><a href="{% url 'projects:regression_train' project.id %}" class="highlight">Continue</a></h4>

  </div>
</div>



{% endblock %}

projects/templates/projects/regression_result.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="project-result">
  <div class="project">
    <div class="result-display">
    <h2>The algorithm you used: {{ project.algorithm_selected }}</h2>
    <h2>The unlabeled data you input: {{ project.unlabeled_data }} </h2>
    <h2>The training result: {{ project.predict_result }}</h2>
  </div>
    <div class="comment-highlight">
    <h3><a href = "{% url 'projects:comment' project.id %}">Add Comment</a></h3>
  </div>
</div>



{% endblock %}

projects/templates/projects/regression_train.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="project-training">
  <div class="project">
    <h2>{{ project.title }}</h2>

    <h3>The result of traning: </h3>
    <pre>{{ project.accurate_list }}</pre>

      <h2>The most suitable algorithm for your project is: {{ project.algorithm_selected }}</h2>
      <h2>The mean squared error rate is: {{ project.mean_squared_error }}</h2>

        <div class="continue">
          <h3><a href="{% url 'projects:regression_predict' project.id %}" class="highlight">Continue </a></h3>
        </div>
</div>
</div>



{% endblock %}

projects/templates/projects/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <h3> {{ project.title }}</h3>
</body>
</html>