FinalProject_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from projects import views as project_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import handler500

handler500 = project_views.page_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('', project_views.project_list, name='home'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG is False:
#     urlpatterns += patterns('', url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT, }), )

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout')
]

projects/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler500

handler500 = views.page_error
app_name = 'projects'
urlpatterns = [
    path('', views.project_list, name="list"),
    path('initial/', views.create_initial, name="initial"),
    path('classification_create/', views.classification_create, name="classification_create"),
    path('regression_create/', views.regression_create, name="regression_create"),
    path('classification_process/<int:project_id>/', views.classification_process, name="classification_process"),
    path('regression_process/<int:project_id>/', views.regression_process, name="regression_process"),
    path('classification_train/<int:project_id>/', views.classification_train, name="classification_train"),
    path('regression_train/<int:project_id>/', views.regression_train, name="regression_train"),
    path('classification_predict/<int:project_id>/', views.classification_predict, name="classification_predict"),
    path('regression_predict/<int:project_id>/', views.regression_predict, name="regression_predict"),
    path('classification_result/<int:project_id>/', views.classification_result, name="classification_result"),
    path('regression_result/<int:project_id>/', views.regression_result, name="regression_result"),
    path('project_comment/<int:project_id>/', views.project_addcomment, name="comment"),
    path('individual/<slug:user_name>/', views.individual_list, name="individual_list"),
    path('<int:project_id>/', views.project_detail, name="detail"),


]

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Final Project - Mingzhao</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <!-- <script src="static/preloader.js"></script> -->

    <body>
      <!-- <div id="overlay">
        <div class="spinner"></div>
      </div> -->

        <header class="wrapper">
            <h1><a href="{% url 'projects:list' %}">Home Page</a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'projects:initial' %}" class="highlight">New Project</a></li>
                    <li><a href="{% url 'projects:individual_list' request.user.username %}" class="highlight">Check My Projects</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>